name: gapsec
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  #SPLASH SCREEN
  animated_splash_screen: ^1.3.0
  #Page Trans
  page_transition: ^2.1.0
  #ANIMATED TEXT
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
  fonts:
    - family: HorrorFont
      fonts:
        - asset: assets/fonts/horrorFont.ttf
          style: normal
